In [2]:
import pandas as pd

In [6]:
base_file_path = 'data/'

df = pd.read_csv("data/polished3_with_moy_gdp.csv")
df.columns

Index(['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games',
       'Year', 'Season', 'City', 'Sport', 'Event', 'Medal', 'Won Medal', 'BMI',
       'GDP'],
      dtype='object')

In [7]:
used_columns = ['NOC', 'Sex', 'Age', 'Height', 'Weight', 'Sport', 'Event']

df = df[used_columns]
sport_df = df.drop(columns=['Event'])
event_df = df.drop(columns=['Sport'])

In [10]:
# for numerical columns, get a average value for each sport/event having a separated row for Men and Woman
# for categorical columns, get the most common value for each sport/event (in this case is only the NOC country)

def process_sports_data(sports_df, eventOrSport):
    # Identify numerical columns
    numerical_columns = sports_df.select_dtypes(include=['number']).columns

    # Group by Sport and Gender
    def aggregate_func(group):
        averages = group[numerical_columns].mean()
        most_common_noc = group['NOC'].mode()[0] if not group['NOC'].mode().empty else None
        return pd.Series({**averages.to_dict(), 'NOC': most_common_noc})

    result = (
        sports_df
        .groupby([eventOrSport, 'Sex'])
        .apply(aggregate_func)
        .reset_index()
    )

    return result

In [11]:
sport_df = process_sports_data(sport_df, 'Sport')
event_df = process_sports_data(event_df, 'Event')

display(sport_df.head())
display(event_df.head())

/tmp/ipykernel_81795/646806740.py:17: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(aggregate_func)
/tmp/ipykernel_81795/646806740.py:17: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(aggregate_func)

       Sport Sex        Age      Height     Weight  NOC
0    Archery   F  25.694224  167.181200  62.013590  CHN
1    Archery   M  26.795591  178.609218  77.092184  USA
2  Athletics   F  25.271651  169.354536  60.187641  USA
3  Athletics   M  25.635284  180.259659  74.315593  USA
4  Badminton   F  25.200000  168.456061  61.586364  CHN

                          Event Sex        Age      Height     Weight  NOC
0      Archery Men's Individual   M  27.123100  178.323708  76.656535  USA
1            Archery Men's Team   M  26.161765  179.161765  77.935294  USA
2    Archery Women's Individual   F  26.094340  167.056604  61.758148  CHN
3          Archery Women's Team   F  24.916667  167.423333  62.510000  CHN
4  Athletics Men's 1,500 metres   M  24.436950  178.281525  65.104106  USA

In [12]:
sport_df.to_csv(base_file_path + 'yourSports.csv', index=False)
event_df.to_csv(base_file_path + 'yourEvents.csv', index=False)

In [17]:
sport_df.to_dict('records')

[{'Sport': 'Archery',
  'Sex': 'F',
  'Age': 25.69422423556059,
  'Height': 167.18120045300114,
  'Weight': 62.013590033975085,
  'NOC': 'CHN'},
 {'Sport': 'Archery',
  'Sex': 'M',
  'Age': 26.795591182364728,
  'Height': 178.60921843687376,
  'Weight': 77.09218436873748,
  'NOC': 'USA'},
 {'Sport': 'Athletics',
  'Sex': 'F',
  'Age': 25.27165084646247,
  'Height': 169.35453566885215,
  'Weight': 60.18764066934142,
  'NOC': 'USA'},
 {'Sport': 'Athletics',
  'Sex': 'M',
  'Age': 25.635284190223615,
  'Height': 180.25965885118438,
  'Weight': 74.31559279127238,
  'NOC': 'USA'},
 {'Sport': 'Badminton',
  'Sex': 'F',
  'Age': 25.2,
  'Height': 168.45606060606062,
  'Weight': 61.586363636363636,
  'NOC': 'CHN'},
 {'Sport': 'Badminton',
  'Sex': 'M',
  'Age': 26.364672364672366,
  'Height': 179.63960113960113,
  'Weight': 74.36253561253561,
  'NOC': 'CHN'},
 {'Sport': 'Baseball',
  'Sex': 'M',
  'Age': 26.3096926713948,
  'Height': 182.59929078014184,
  'Weight': 85.71808510638297,
  'NOC': 'JPN'},
 {'Sport': 'Basketball',
  'Sex': 'F',
  'Age': 25.666951323654995,
  'Height': 182.5072587532024,
  'Weight': 73.70794192997438,
  'NOC': 'USA'},
 {'Sport': 'Basketball',
  'Sex': 'M',
  'Age': 25.60903284671533,
  'Height': 196.0410583941606,
  'Weight': 92.36587591240875,
  'NOC': 'USA'},
 {'Sport': 'Beach Volleyball',
  'Sex': 'F',
  'Age': 28.27169811320755,
  'Height': 178.90188679245284,
  'Weight': 68.35094339622641,
  'NOC': 'AUS'},
 {'Sport': 'Beach Volleyball',
  'Sex': 'M',
  'Age': 29.974358974358974,
  'Height': 193.28937728937728,
  'Weight': 89.51282051282051,
  'NOC': 'BRA'},
 {'Sport': 'Boxing',
  'Sex': 'F',
  'Age': 26.728813559322035,
  'Height': 168.67796610169492,
  'Weight': 61.644067796610166,
  'NOC': 'CHN'},
 {'Sport': 'Boxing',
  'Sex': 'M',
  'Age': 23.273982558139537,
  'Height': 172.88517441860466,
  'Weight': 65.1935562015504,
  'NOC': 'DEU'},
 {'Sport': 'Canoeing',
  'Sex': 'F',
  'Age': 25.296616837136114,
  'Height': 169.6475216365067,
  'Weight': 64.88906372934697,
  'NOC': 'DEU'},
 {'Sport': 'Canoeing',
  'Sex': 'M',
  'Age': 25.42874513618677,
  'Height': 181.37110894941634,
  'Weight': 80.12791828793775,
  'NOC': 'DEU'},
 {'Sport': 'Cycling',
  'Sex': 'F',
  'Age': 26.908071748878925,
  'Height': 168.0149476831091,
  'Weight': 59.770553064275035,
  'NOC': 'DEU'},
 {'Sport': 'Cycling',
  'Sex': 'M',
  'Age': 24.776001291989665,
  'Height': 177.94767441860466,
  'Weight': 72.25177648578811,
  'NOC': 'DEU'},
 {'Sport': 'Diving',
  'Sex': 'F',
  'Age': 21.629828326180256,
  'Height': 161.31330472103005,
  'Weight': 53.607296137339056,
  'NOC': 'DEU'},
 {'Sport': 'Diving',
  'Sex': 'M',
  'Age': 22.775049115913557,
  'Height': 171.70825147347742,
  'Weight': 67.02799607072691,
  'NOC': 'DEU'},
 {'Sport': 'Equestrianism',
  'Sex': 'F',
  'Age': 34.21484716157205,
  'Height': 167.87248908296942,
  'Weight': 58.570305676855895,
  'NOC': 'USA'},
 {'Sport': 'Equestrianism',
  'Sex': 'M',
  'Age': 34.23414940364093,
  'Height': 176.73948524795983,
  'Weight': 71.04252981795355,
  'NOC': 'DEU'},
 {'Sport': 'Fencing',
  'Sex': 'F',
  'Age': 26.04951065054692,
  'Height': 168.9769717904433,
  'Weight': 60.65486470926886,
  'NOC': 'RUS'},
 {'Sport': 'Fencing',
  'Sex': 'M',
  'Age': 26.96339779005525,
  'Height': 180.6487108655617,
  'Weight': 75.39330110497238,
  'NOC': 'FRA'},
 {'Sport': 'Football',
  'Sex': 'F',
  'Age': 24.915650406504064,
  'Height': 167.6819105691057,
  'Weight': 60.925813008130085,
  'NOC': 'BRA'},
 {'Sport': 'Football',
  'Sex': 'M',
  'Age': 23.094646271510516,
  'Height': 177.8272785213512,
  'Weight': 73.18706182281709,
  'NOC': 'BRA'},
 {'Sport': 'Golf',
  'Sex': 'F',
  'Age': 27.10909090909091,
  'Height': 168.96363636363637,
  'Weight': 63.43636363636364,
  'NOC': 'KOR'},
 {'Sport': 'Golf',
  'Sex': 'M',
  'Age': 32.15094339622642,
  'Height': 179.32075471698113,
  'Weight': 79.24528301886792,
  'NOC': 'USA'},
 {'Sport': 'Gymnastics',
  'Sex': 'F',
  'Age': 18.562878467821434,
  'Height': 155.9349387410224,
  'Weight': 47.36741304041684,
  'NOC': 'DEU'},
 {'Sport': 'Gymnastics',
  'Sex': 'M',
  'Age': 23.66890243902439,
  'Height': 167.52916666666667,
  'Weight': 63.10238821138211,
  'NOC': 'DEU'},
 {'Sport': 'Handball',
  'Sex': 'F',
  'Age': 26.06456820016142,
  'Height': 174.81194511702986,
  'Weight': 68.87409200968523,
  'NOC': 'KOR'},
 {'Sport': 'Handball',
  'Sex': 'M',
  'Age': 26.836558044806516,
  'Height': 188.94144602851324,
  'Weight': 89.5,
  'NOC': 'DEU'},
 {'Sport': 'Hockey',
  'Sex': 'F',
  'Age': 25.407913669064747,
  'Height': 166.21007194244604,
  'Weight': 60.53093525179856,
  'NOC': 'DEU'},
 {'Sport': 'Hockey',
  'Sex': 'M',
  'Age': 25.756317689530686,
  'Height': 176.8783393501805,
  'Weight': 73.34765342960289,
  'NOC': 'ESP'},
 {'Sport': 'Judo',
  'Sex': 'F',
  'Age': 25.30421686746988,
  'Height': 166.21485943775102,
  'Weight': 67.02560240963855,
  'NOC': 'JPN'},
 {'Sport': 'Judo',
  'Sex': 'M',
  'Age': 25.457764505119453,
  'Height': 177.47952218430035,
  'Weight': 83.7585324232082,
  'NOC': 'DEU'},
 {'Sport': 'Modern Pentathlon',
  'Sex': 'F',
  'Age': 25.524390243902438,
  'Height': 170.0731707317073,
  'Weight': 58.3109756097561,
  'NOC': 'GBR'},
 {'Sport': 'Modern Pentathlon',
  'Sex': 'M',
  'Age': 26.247363374880152,
  'Height': 179.41418983700862,
  'Weight': 72.15723873441995,
  'NOC': 'DEU'},
 {'Sport': 'Rhythmic Gymnastics',
  'Sex': 'F',
  'Age': 18.818330605564647,
  'Height': 167.83633387888707,
  'Weight': 48.76923076923077,
  'NOC': 'BGR'},
 {'Sport': 'Rowing',
  'Sex': 'F',
  'Age': 25.44062205466541,
  'Height': 176.76814326107447,
  'Weight': 70.10226201696513,
  'NOC': 'DEU'},
 {'Sport': 'Rowing',
  'Sex': 'M',
  'Age': 25.493042497179392,
  'Height': 187.3798420458819,
  'Weight': 84.27538548326439,
  'NOC': 'DEU'},
 {'Sport': 'Rugby Sevens',
  'Sex': 'F',
  'Age': 26.184931506849313,
  'Height': 167.63698630136986,
  'Weight': 66.5958904109589,
  'NOC': 'BRA'},
 {'Sport': 'Rugby Sevens',
  'Sex': 'M',
  'Age': 25.980132450331126,
  'Height': 182.83443708609272,
  'Weight': 91.00662251655629,
  'NOC': 'ARG'},
 {'Sport': 'Sailing',
  'Sex': 'F',
  'Age': 26.67816091954023,
  'Height': 169.51609195402298,
  'Weight': 62.774712643678164,
  'NOC': 'ESP'},
 {'Sport': 'Sailing',
  'Sex': 'M',
  'Age': 29.822015915119362,
  'Height': 180.32201591511935,
  'Weight': 78.84535809018567,
  'NOC': 'DEU'},
 {'Sport': 'Shooting',
  'Sex': 'F',
  'Age': 29.25577156743621,
  'Height': 164.89489671931958,
  'Weight': 61.1357837181045,
  'NOC': 'CHN'},
 {'Sport': 'Shooting',
  'Sex': 'M',
  'Age': 32.85544889892716,
  'Height': 176.16337285902503,
  'Weight': 77.93675889328063,
  'NOC': 'DEU'},
 {'Sport': 'Softball',
  'Sex': 'F',
  'Age': 26.22902494331066,
  'Height': 169.42857142857142,
  'Weight': 67.47165532879819,
  'NOC': 'AUS'},
 {'Sport': 'Swimming',
  'Sex': 'F',
  'Age': 19.582195063503473,
  'Height': 171.5699736400671,
  'Weight': 61.50449317038102,
  'NOC': 'DEU'},
 {'Sport': 'Swimming',
  'Sex': 'M',
  'Age': 21.493355979618343,
  'Height': 184.53521830352682,
  'Weight': 78.06149465481067,
  'NOC': 'USA'},
 {'Sport': 'Synchronized Swimming',
  'Sex': 'F',
  'Age': 22.48527679623086,
  'Height': 168.489988221437,
  'Weight': 55.85630153121319,
  'NOC': 'JPN'},
 {'Sport': 'Table Tennis',
  'Sex': 'F',
  'Age': 25.971830985915492,
  'Height': 165.02582159624413,
  'Weight': 57.9424882629108,
  'NOC': 'CHN'},
 {'Sport': 'Table Tennis',
  'Sex': 'M',
  'Age': 27.271631982475355,
  'Height': 176.97261774370207,
  'Weight': 71.32201533406352,
  'NOC': 'CHN'},
 {'Sport': 'Taekwondo',
  'Sex': 'F',
  'Age': 23.444827586206898,
  'Height': 170.76896551724138,
  'Weight': 61.16034482758621,
  'NOC': 'AUS'},
 {'Sport': 'Taekwondo',
  'Sex': 'M',
  'Age': 24.68954248366013,
  'Height': 182.41830065359477,
  'Weight': 74.65359477124183,
  'NOC': 'AUS'},
 {'Sport': 'Tennis',
  'Sex': 'F',
  'Age': 24.11007268951194,
  'Height': 172.41536863966772,
  'Weight': 62.0944963655244,
  'NOC': 'USA'},
 {'Sport': 'Tennis',
  'Sex': 'M',
  'Age': 26.006930693069307,
  'Height': 185.07821782178218,
  'Weight': 78.90792079207921,
  'NOC': 'USA'},
 {'Sport': 'Trampolining',
  'Sex': 'F',
  'Age': 25.533333333333335,
  'Height': 161.73333333333332,
  'Weight': 52.89333333333333,
  'NOC': 'CAN'},
 {'Sport': 'Trampolining',
  'Sex': 'M',
  'Age': 24.7972972972973,
  'Height': 171.45945945945945,
  'Weight': 65.83783783783784,
  'NOC': 'RUS'},
 {'Sport': 'Triathlon',
  'Sex': 'F',
  'Age': 27.946360153256705,
  'Height': 166.97318007662835,
  'Weight': 54.724137931034484,
  'NOC': 'AUS'},
 {'Sport': 'Triathlon',
  'Sex': 'M',
  'Age': 27.852272727272727,
  'Height': 180.1969696969697,
  'Weight': 68.79545454545455,
  'NOC': 'FRA'},
 {'Sport': 'Volleyball',
  'Sex': 'F',
  'Age': 24.48494983277592,
  'Height': 179.49498327759198,
  'Weight': 69.33377926421404,
  'NOC': 'JPN'},
 {'Sport': 'Volleyball',
  'Sex': 'M',
  'Age': 25.87909604519774,
  'Height': 193.26553672316385,
  'Weight': 86.93333333333334,
  'NOC': 'BRA'},
 {'Sport': 'Water Polo',
  'Sex': 'F',
  'Age': 25.16188524590164,
  'Height': 175.56352459016392,
  'Weight': 70.18032786885246,
  'NOC': 'AUS'},
 {'Sport': 'Water Polo',
  'Sex': 'M',
  'Age': 25.861717612809315,
  'Height': 187.12081513828238,
  'Weight': 87.64143619602135,
  'NOC': 'ITA'},
 {'Sport': 'Weightlifting',
  'Sex': 'F',
  'Age': 24.03913043478261,
  'Height': 160.4673913043478,
  'Weight': 67.75108695652175,
  'NOC': 'CHN'},
 {'Sport': 'Weightlifting',
  'Sex': 'M',
  'Age': 25.49220396123051,
  'Height': 169.13653603034135,
  'Weight': 81.94058154235145,
  'NOC': 'DEU'},
 {'Sport': 'Wrestling',
  'Sex': 'F',
  'Age': 25.31023102310231,
  'Height': 163.86798679867988,
  'Weight': 60.554455445544555,
  'NOC': 'CAN'},
 {'Sport': 'Wrestling',
  'Sex': 'M',
  'Age': 25.678221059516023,
  'Height': 172.96664486592545,
  'Weight': 76.60453455417485,
  'NOC': 'USA'}]